import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.EOFException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Locale;

public class guiTwo extends JFrame {

    public JPanel mainPanel;
    public JPanel topPanel;
    public JLabel title;
    public JTextArea bookField;

    FileIO fio = new FileIO();
    Book bo = new Book();

    //ArrayList<Book> booksList;


    public guiTwo() throws IOException, ClassNotFoundException {
        setContentPane(mainPanel);
        setSize(800, 450);
        setVisible(true);
        bookField.setEditable(false);
        //ArrayList Approach
        ArrayList<Book> booksList = fio.readFromFile();
        for (Book b : booksList) {
            System.out.println(b.bookID + "\t" + b.bookName + "\t" + b.authorName + "\t" + b.publication + "\t" + b.dateofPublication + "\t" + b.priceofBook);
            bookField.append("\t" + b.bookID + "\t" + b.bookName + "\t" + b.authorName + "\t" + b.publication + "\t" + b.dateofPublication + "\t" + b.priceofBook + "\n");
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        mainPanel.setMinimumSize(new Dimension(800, 450));
        mainPanel.setPreferredSize(new Dimension(800, 450));
        topPanel = new JPanel();
        topPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow"));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(topPanel, cc.xy(1, 1));
        title = new JLabel();
        Font titleFont = this.$$$getFont$$$("Segoe UI", Font.PLAIN, 18, title.getFont());
        if (titleFont != null) title.setFont(titleFont);
        title.setHorizontalAlignment(0);
        title.setHorizontalTextPosition(0);
        title.setText("Book Details");
        topPanel.add(title, cc.xy(1, 1));
        bookField = new JTextArea();
        bookField.setMinimumSize(new Dimension(700, 350));
        bookField.setPreferredSize(new Dimension(700, 350));
        mainPanel.add(bookField, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.CENTER));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
